import { Theme } from "../../../typings/types.js";

const baseExtra = {
  "--active-sideabr-item-bg": "transparent",
  "--active-item": "transparent",
  "--titlebar-border": "transparent",
  "--tab-wrapper-bg": "transparent",
  "--splitter-active-color": "transparent",
  "--scrollbar-color": "transparent",
  "--hover-filetree-node-background": "transparent",
  "--active--scrollbar-color": "transparent",
  "--hover--scrollbar-color": "transparent",
} as const;

export const DarkTheme: Theme = {
  name: "Meridia Dark",
  kind: "dark",
  colors: {
    ...baseExtra,
    "--main-bg": "#1A1A1A",
    "--titlebar-bg": "#1A1A1A",
    "--activity-bar-bg": "#1A1A1A",
    "--sidebar-bg": "#1A1A1A",
    "--extension-bg": "#1A1A1A",
    "--content-bg": "#1A1A1A",
    "--command-palette-bg": "#1e1e22",
    "--tab-bg": "#212121",
    "--tab-wrapper-bg": "#1A1A1A",
    "--active-border": "#93D479",
    "--active-icon-color": "#93D479",
    "--editor-bg": "#212121",
    "--active-text-color": "#93D479",
    "--settings-bg": "#101012",
    "--settings-sidebar-bg": "#1e1e22",
    "--terminal-bg": "#191A1B",
    "--terminal-tabs-bg": "#191A1B",
    "--input-bg": "#1f1f23",
    "--select-bg": "#1f1f23",
    "--tooltip-bg": "#1e1e22",
    "--editor-theme": "dark",
    "--border-color": "#2A2A2A",
    "--focus-color": "#7aa2f7",
    "--text-color": "#d9e0ee",
    "--cursor-color": "#ff6969",
    "--second-text-color": "#7aa2f7",
    "--dark-text-color": "#101012",
    "--icon-color": "#a1a1aa",
    "--hover-bg": "#151515",
    "--window-controls-close-button-hover": "#f38ba8",
    "--text-hover-color": "#ffffff",
    "--icon-hover-bg": "#2e2e32",
    "--dropdown-bg": "#1A1A1A",
    "--submenu-bg": "#1A1A1A",
    "--separator": "#2e2e32",
    "--file-tree-folder-content-border-color": "#424242",
    "--scrollbar-thumb-color": "#3f3f45",
    "--scrollbar-thumb-hover-color": "#5a5a60",
    "--scrollbar-color": "#3f3f45",
    "--hover-filetree-node-background": "#2e2e32",
    "--active--scrollbar-color": "#93D479",
    "--hover--scrollbar-color": "#5a5a60",
    "--splitter-active-color": "#93D479",
    "--titlebar-border": "#2A2A2A",
    "--blue-color": "#7aa2f7",
    "--green-color": "#a6e3a1",
    "--red-color": "#ff6969",
  },
  tokenColors: {
    keyword: "#7aa2f7",
    string: "#a6e3a1",
    number: "#f38ba8",
    function: "#7aa2f7",
    variable: "#d9e0ee",
    type: "#93D479",
    comment: "#6b7280",
  },
  semanticTokens: {
    variable: "#d9e0ee",
    parameter: "#d9e0ee",
    function: "#7aa2f7",
    method: "#7aa2f7",
    class: "#93D479",
    interface: "#93D479",
    enum: "#93D479",
    string: "#a6e3a1",
    number: "#f38ba8",
    boolean: "#f38ba8",
    keyword: "#7aa2f7",
  },
};

export const LightTheme: Theme = {
  name: "Meridia Light",
  kind: "light",
  colors: {
    ...baseExtra,
    "--main-bg": "#ffffff",
    "--titlebar-bg": "#f5f5f5",
    "--footer-bg": "#f5f5f5",
    "--sidebar-bg": "#fafafa",
    "--extension-bg": "#ffffff",
    "--content-bg": "#ffffff",
    "--command-palette-bg": "#f7f7f9",
    "--tab-bg": "#f0f0f0",
    "--tab-wrapper-bg": "#f0f0f0",
    "--active-border": "#3b82f6",
    "--active-icon-color": "#3b82f6",
    "--editor-bg": "#ffffff",
    "--active-text-color": "#3b82f6",
    "--settings-bg": "#ffffff",
    "--settings-sidebar-bg": "#f2f2f4",
    "--terminal-bg": "#ffffff",
    "--terminal-tabs-bg": "#ececec",
    "--input-bg": "#f2f2f2",
    "--select-bg": "#f2f2f2",
    "--tooltip-bg": "#f2f2f4",
    "--editor-theme": "light",
    "--border-color": "#e5e7eb",
    "--focus-color": "#2563eb",
    "--text-color": "#111827",
    "--cursor-color": "#2563eb",
    "--second-text-color": "#2563eb",
    "--dark-text-color": "#101012",
    "--icon-color": "#6b7280",
    "--hover-bg": "#f3f4f6",
    "--window-controls-close-button-hover": "#ef4444",
    "--text-hover-color": "#111827",
    "--icon-hover-bg": "#e5e7eb",
    "--dropdown-bg": "#ffffff",
    "--submenu-bg": "#ffffff",
    "--separator": "#e5e7eb",
    "--file-tree-folder-content-border-color": "#e5e7eb",
    "--scrollbar-thumb-color": "#d1d5db",
    "--scrollbar-thumb-hover-color": "#9ca3af",
    "--scrollbar-color": "#d1d5db",
    "--hover-filetree-node-background": "#e5e7eb",
    "--active--scrollbar-color": "#3b82f6",
    "--hover--scrollbar-color": "#9ca3af",
    "--splitter-active-color": "#3b82f6",
    "--titlebar-border": "#e5e7eb",
    "--blue-color": "#2563eb",
    "--green-color": "#16a34a",
    "--red-color": "#ef4444",
  },
  tokenColors: {
    keyword: "#2563eb",
    string: "#16a34a",
    number: "#ef4444",
    function: "#2563eb",
    variable: "#111827",
    type: "#2563eb",
    comment: "#9ca3af",
  },
  semanticTokens: {
    variable: "#111827",
    parameter: "#111827",
    function: "#2563eb",
    method: "#2563eb",
    class: "#2563eb",
    interface: "#2563eb",
    enum: "#2563eb",
    string: "#16a34a",
    number: "#ef4444",
    boolean: "#ef4444",
    keyword: "#2563eb",
  },
};

export const LightBlueTheme: Theme = {
  name: "Meridia Light Blue",
  kind: "light",
  colors: {
    ...baseExtra,
    "--main-bg": "#ffffff",
    "--titlebar-bg": "#f5f7fa",
    "--footer-bg": "#f5f7fa",
    "--sidebar-bg": "#f9fafb",
    "--extension-bg": "#ffffff",
    "--content-bg": "#ffffff",
    "--command-palette-bg": "#f3f6fb",
    "--tab-bg": "#eef2f8",
    "--tab-wrapper-bg": "#eef2f8",
    "--active-border": "#2563eb",
    "--active-icon-color": "#2563eb",
    "--editor-bg": "#ffffff",
    "--active-text-color": "#2563eb",
    "--settings-bg": "#ffffff",
    "--settings-sidebar-bg": "#f0f4f8",
    "--terminal-bg": "#ffffff",
    "--terminal-tabs-bg": "#e9edf4",
    "--input-bg": "#f3f4f6",
    "--select-bg": "#f3f4f6",
    "--tooltip-bg": "#f0f4f8",
    "--editor-theme": "light",
    "--border-color": "#4178edff",
    "--focus-color": "#2563eb",
    "--text-color": "#1e293b",
    "--cursor-color": "#2563eb",
    "--second-text-color": "#2563eb",
    "--dark-text-color": "#101012",
    "--icon-color": "#64748b",
    "--hover-bg": "#f1f5f9",
    "--window-controls-close-button-hover": "#ef4444",
    "--text-hover-color": "#1e293b",
    "--icon-hover-bg": "#dbeafe",
    "--dropdown-bg": "#ffffff",
    "--submenu-bg": "#ffffff",
    "--separator": "#e2e8f0",
    "--file-tree-folder-content-border-color": "#e2e8f0",
    "--scrollbar-thumb-color": "#cbd5e1",
    "--scrollbar-thumb-hover-color": "#94a3b8",
    "--scrollbar-color": "#cbd5e1",
    "--hover-filetree-node-background": "#e2e8f0",
    "--active--scrollbar-color": "#2563eb",
    "--hover--scrollbar-color": "#94a3b8",
    "--splitter-active-color": "#2563eb",
    "--titlebar-border": "#e2e8f0",
    "--blue-color": "#2563eb",
    "--green-color": "#16a34a",
    "--red-color": "#ef4444",
  },
  tokenColors: {
    keyword: "#2563eb",
    string: "#16a34a",
    number: "#ef4444",
    function: "#2563eb",
    variable: "#1e293b",
    type: "#2563eb",
    comment: "#94a3b8",
  },
  semanticTokens: {
    variable: "#1e293b",
    parameter: "#1e293b",
    function: "#2563eb",
    method: "#2563eb",
    class: "#2563eb",
    interface: "#2563eb",
    enum: "#2563eb",
    string: "#16a34a",
    number: "#ef4444",
    boolean: "#ef4444",
    keyword: "#2563eb",
  },
};

export const GoatedDarkTheme: Theme = {
  name: "Meridia Goated Dark",
  kind: "dark",
  colors: {
    ...baseExtra,
    "--main-bg": "#0b0c10",
    "--titlebar-bg": "#0b0c10",
    "--footer-bg": "#0b0c10",
    "--sidebar-bg": "#111317",
    "--extension-bg": "#0b0c10",
    "--content-bg": "#0b0c10",
    "--command-palette-bg": "#121417",
    "--tab-bg": "#1a1c20",
    "--tab-wrapper-bg": "#1a1c20",
    "--active-border": "#3b82f6",
    "--active-icon-color": "#3b82f6",
    "--editor-bg": "#1a1c20",
    "--active-text-color": "#3b82f6",
    "--settings-bg": "#0d0f12",
    "--settings-sidebar-bg": "#16181c",
    "--terminal-bg": "#1a1c20",
    "--terminal-tabs-bg": "#101215",
    "--input-bg": "#15171a",
    "--select-bg": "#15171a",
    "--tooltip-bg": "#16181c",
    "--editor-theme": "dark",
    "--border-color": "#22242a",
    "--focus-color": "#60a5fa",
    "--text-color": "#e2e8f0",
    "--cursor-color": "#f87171",
    "--second-text-color": "#3b82f6",
    "--dark-text-color": "#0b0c10",
    "--icon-color": "#94a3b8",
    "--hover-bg": "#101215",
    "--window-controls-close-button-hover": "#ef4444",
    "--text-hover-color": "#ffffff",
    "--icon-hover-bg": "#2a2e36",
    "--dropdown-bg": "#0b0c10",
    "--submenu-bg": "#0b0c10",
    "--separator": "#2a2e36",
    "--file-tree-folder-content-border-color": "#33363f",
    "--scrollbar-thumb-color": "#2e3138",
    "--scrollbar-thumb-hover-color": "#475569",
    "--scrollbar-color": "#2e3138",
    "--hover-filetree-node-background": "#2a2e36",
    "--active--scrollbar-color": "#3b82f6",
    "--hover--scrollbar-color": "#475569",
    "--splitter-active-color": "#3b82f6",
    "--titlebar-border": "#22242a",
    "--blue-color": "#3b82f6",
    "--green-color": "#22c55e",
    "--red-color": "#ef4444",
  },
  tokenColors: {
    keyword: "#3b82f6",
    string: "#22c55e",
    number: "#f87171",
    function: "#60a5fa",
    variable: "#e2e8f0",
    type: "#93c5fd",
    comment: "#6b7280",
  },
  semanticTokens: {
    variable: "#e2e8f0",
    parameter: "#e2e8f0",
    function: "#60a5fa",
    method: "#60a5fa",
    class: "#93c5fd",
    interface: "#93c5fd",
    enum: "#93c5fd",
    string: "#22c55e",
    number: "#f87171",
    boolean: "#f87171",
    keyword: "#3b82f6",
  },
};

export const PyCharmDarkTheme: Theme = {
  name: "Meridia PyCharm Dark",
  kind: "dark",
  colors: {
    ...baseExtra,
    "--main-bg": "#2B2B2B",
    "--titlebar-bg": "#2B2B2B",
    "--footer-bg": "#2B2B2B",
    "--sidebar-bg": "#313335",
    "--extension-bg": "#2B2B2B",
    "--content-bg": "#2B2B2B",
    "--command-palette-bg": "#323232",
    "--tab-bg": "#3C3F41",
    "--tab-wrapper-bg": "#3C3F41",
    "--active-border": "#4FC1FF",
    "--active-icon-color": "#4FC1FF",
    "--editor-bg": "#2B2B2B",
    "--active-text-color": "#4FC1FF",
    "--settings-bg": "#2B2B2B",
    "--settings-sidebar-bg": "#3C3F41",
    "--terminal-bg": "#2B2B2B",
    "--terminal-tabs-bg": "#262626",
    "--input-bg": "#323232",
    "--select-bg": "#323232",
    "--tooltip-bg": "#3C3F41",
    "--editor-theme": "dark",
    "--border-color": "#3C3F41",
    "--focus-color": "#4FC1FF",
    "--text-color": "#A9B7C6",
    "--cursor-color": "#FFCC00",
    "--second-text-color": "#4FC1FF",
    "--dark-text-color": "#1A1A1A",
    "--icon-color": "#A9B7C6",
    "--hover-bg": "#3C3F41",
    "--window-controls-close-button-hover": "#FF5555",
    "--text-hover-color": "#FFFFFF",
    "--icon-hover-bg": "#45494B",
    "--dropdown-bg": "#2B2B2B",
    "--submenu-bg": "#2B2B2B",
    "--separator": "#45494B",
    "--file-tree-folder-content-border-color": "#4C5052",
    "--scrollbar-thumb-color": "#3C3F41",
    "--scrollbar-thumb-hover-color": "#5A5A5A",
    "--scrollbar-color": "#3C3F41",
    "--hover-filetree-node-background": "#45494B",
    "--active--scrollbar-color": "#4FC1FF",
    "--hover--scrollbar-color": "#5A5A5A",
    "--splitter-active-color": "#4FC1FF",
    "--titlebar-border": "#3C3F41",
    "--blue-color": "#4FC1FF",
    "--green-color": "#6A8759",
    "--red-color": "#FF5555",
  },
  tokenColors: {
    keyword: "#CC7832",
    string: "#6A8759",
    number: "#6897BB",
    function: "#FFC66D",
    variable: "#A9B7C6",
    type: "#4FC1FF",
    comment: "#808080",
  },
  semanticTokens: {
    variable: "#A9B7C6",
    parameter: "#A9B7C6",
    function: "#FFC66D",
    method: "#FFC66D",
    class: "#4FC1FF",
    interface: "#4FC1FF",
    enum: "#4FC1FF",
    string: "#6A8759",
    number: "#6897BB",
    boolean: "#6897BB",
    keyword: "#CC7832",
  },
};

export const ManojKhandelwal: Theme = {
  name: "ManojKhandelwal",
  kind: "dark",
  colors: {
    ...baseExtra,
    "--main-bg": "#3C3F41",
    "--titlebar-bg": "#4B6EAF",
    "--footer-bg": "#4B6EAF",
    "--sidebar-bg": "#282828",
    "--active-sideabr-item-bg": "transparent",
    "--active-item": "transparent",
    "--titlebar-border": "#282828",
    "--content-bg": "#3C3F41",
    "--command-palette-bg": "#323437",
    "--tab-bg": "#3c3f41",
    "--tab-wrapper-bg": "#B28815",
    "--splitter-active-color": "#B28815",
    "--scrollbar-color": "#4B6EAF",
    "--hover-filetree-node-background": "#B28815",
    "--active--scrollbar-color": "#B28815",
    "--hover--scrollbar-color": "#B28815",
    "--active-border": "#8be9fd",
    "--active-icon-color": "#8be9fd",
    "--editor-bg": "#282828",
    "--active-text-color": "#8be9fd",
    "--settings-bg": "#2b2d30",
    "--settings-sidebar-bg": "#2b2d30",
    "--terminal-bg": "#3C3F41",
    "--terminal-tabs-bg": "#262626",
    "--input-bg": "#323232",
    "--select-bg": "#323232",
    "--tooltip-bg": "#3C3F41",
    "--editor-theme": "dark",
    "--border-color": "#3c3f41",
    "--focus-color": "#8be9fd",
    "--text-color": "#f8f8f2",
    "--cursor-color": "#ff79c6",
    "--second-text-color": "#8be9fd",
    "--dark-text-color": "#1a1a1a",
    "--icon-color": "#a9b7c6",
    "--hover-bg": "#3c3f41",
    "--window-controls-close-button-hover": "#ff5555",
    "--text-hover-color": "#ffffff",
    "--icon-hover-bg": "#45494b",
    "--dropdown-bg": "#2b2d30",
    "--submenu-bg": "#2b2d30",
    "--separator": "#45494b",
    "--file-tree-folder-content-border-color": "#4c5052",
    "--scrollbar-thumb-color": "#3c3f41",
    "--scrollbar-thumb-hover-color": "#5a5a5a",
    "--blue-color": "#8be9fd",
    "--green-color": "#50fa7b",
    "--red-color": "#ff5555",
  },
  tokenColors: {
    keyword: "#ff79c6",
    string: "#f1fa8c",
    number: "#bd93f9",
    function: "#50fa7b",
    variable: "#f8f8f2",
    type: "#8be9fd",
    comment: "#6272a4",
  },
  semanticTokens: {
    variable: "#f8f8f2",
    parameter: "#f8f8f2",
    function: "#50fa7b",
    method: "#50fa7b",
    class: "#8be9fd",
    interface: "#8be9fd",
    enum: "#8be9fd",
    string: "#f1fa8c",
    number: "#bd93f9",
    boolean: "#bd93f9",
    keyword: "#ff79c6",
  },
};

export const VSCodeDarkPlusTheme: Theme = {
  name: "Meridia VSCode Dark+",
  kind: "dark",
  colors: {
    ...baseExtra,
    "--main-bg": "#1e1e1e",
    "--titlebar-bg": "#1f1f1f",
    "--footer-bg": "#1f1f1f",
    "--sidebar-bg": "#252526",
    "--extension-bg": "#1e1e1e",
    "--content-bg": "#1e1e1e",
    "--command-palette-bg": "#252526",
    "--tab-bg": "#2d2d2d",
    "--tab-wrapper-bg": "#2d2d2d",
    "--active-border": "#007acc",
    "--active-icon-color": "#007acc",
    "--editor-bg": "#1e1e1e",
    "--active-text-color": "#007acc",
    "--settings-bg": "#1e1e1e",
    "--settings-sidebar-bg": "#252526",
    "--terminal-bg": "#1e1e1e",
    "--terminal-tabs-bg": "#2d2d2d",
    "--input-bg": "#333333",
    "--select-bg": "#333333",
    "--tooltip-bg": "#252526",
    "--editor-theme": "dark",
    "--border-color": "#3c3c3c",
    "--focus-color": "#007acc",
    "--text-color": "#d4d4d4",
    "--cursor-color": "#aeafad",
    "--second-text-color": "#007acc",
    "--dark-text-color": "#0f0f0f",
    "--icon-color": "#c5c5c5",
    "--hover-bg": "#2a2a2a",
    "--window-controls-close-button-hover": "#f14c4c",
    "--text-hover-color": "#ffffff",
    "--icon-hover-bg": "#37373d",
    "--dropdown-bg": "#1e1e1e",
    "--submenu-bg": "#1e1e1e",
    "--separator": "#3c3c3c",
    "--file-tree-folder-content-border-color": "#3c3c3c",
    "--scrollbar-thumb-color": "#4f4f4f",
    "--scrollbar-thumb-hover-color": "#5f5f5f",
    "--scrollbar-color": "#4f4f4f",
    "--hover-filetree-node-background": "#2a2a2a",
    "--active--scrollbar-color": "#007acc",
    "--hover--scrollbar-color": "#5f5f5f",
    "--splitter-active-color": "#007acc",
    "--titlebar-border": "#3c3c3c",
    "--blue-color": "#569cd6",
    "--green-color": "#6a9955",
    "--red-color": "#f44747",
  },
  tokenColors: {
    keyword: "#569cd6",
    string: "#ce9178",
    number: "#b5cea8",
    function: "#dcdcaa",
    variable: "#9cdcfe",
    type: "#4ec9b0",
    comment: "#6a9955",
  },
  semanticTokens: {
    variable: "#9cdcfe",
    parameter: "#9cdcfe",
    function: "#dcdcaa",
    method: "#dcdcaa",
    class: "#4ec9b0",
    interface: "#4ec9b0",
    enum: "#4ec9b0",
    string: "#ce9178",
    number: "#b5cea8",
    boolean: "#b5cea8",
    keyword: "#569cd6",
  },
};
